# Numpy: Numerical Python

In [ ]:
!pip install numpy         !conda install numpy

In [1]:
import numpy as np

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__

In [3]:
len(dir(np))

598

In [4]:
a = 8
type(a)
#One integer takes up 4 bytes of memory space.

int

In [5]:
b = "A"
type(b)
#One character takes up 4 bytes of space.

str

In [ ]:
c = "Akash"
#20 bytes of space. 

#### Base Python Data Structure properties:

In [ ]:
#1.They are 1-D data structures.
#2.They can store homogenous and heterogenous data.
#3.Lists, Tuples, Dictionaries, Sets
#4.Broadcasting is not allowed in base python.
#5. Vectorization is allowed.
#6. No efficient memory management is done unlike numpy module.

#### Numpy Data Structures properties:

In [ ]:
#1. It is n-dimensional.
#2. It is a homogenous data structure.
#3. Arrays or matrices
#4. Braodcasting is allowed.
#5. Vectorization(one-to_one mapping) is allowed.
#6. EMM (EFFICIENT MEMORY MANAGEMENT). iT SAVES MUCH MEMORY SPACE.

**In numpy module (in n-dimensional data....Arrays(Matrix_2D)), str datatype is not used instead object datatype is used.**

# 1. Creating a Numpy array using a list

In [ ]:
#obj = Numpy()
#obj.array()
modulename.methodname(parameters)
#how to get the parameters of any method.
modulename.methodname?                 #mandatory step

In [9]:
lp = list(range(10,101,10))
lp

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [ ]:
#t = (1,2,3)
#a = np.array(t)

In [10]:
a1 = np.array(lp)
a1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

**5 very basic methods we should always use to check the array**

In [11]:
a1.shape   #10 rows,1 columns

(10,)

In [12]:
a1.size    #it is same as len()

10

In [13]:
a1.ndim   #dimension

1

In [14]:
a1.dtype  #what kind of data is kept in an array

dtype('int32')

**Arrays are homogenous data structures.**

In [15]:
a1.nbytes  #how much memory space it is occupying?

40

# 2. Creating a array using range() directly.

In [16]:
a2 = np.array(range(5,101,5))
a2

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [17]:
a2.size

20

# 3.Creating n-dimensional(2-D array) from one 1-D array.

In [19]:
a1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [20]:
a1 = a1.reshape((2,5))
a1

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [21]:
a11 = a1.reshape((5,2))
a11

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [22]:
a2

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [23]:
a2.size

20

In [24]:
a2 = a2.reshape((4,5))
a2

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100]])

In [26]:
a3 = np.array(range(10,1001,10))
a3.size

100

In [27]:
a3 = a3.reshape((20,5))
a3

array([[  10,   20,   30,   40,   50],
       [  60,   70,   80,   90,  100],
       [ 110,  120,  130,  140,  150],
       [ 160,  170,  180,  190,  200],
       [ 210,  220,  230,  240,  250],
       [ 260,  270,  280,  290,  300],
       [ 310,  320,  330,  340,  350],
       [ 360,  370,  380,  390,  400],
       [ 410,  420,  430,  440,  450],
       [ 460,  470,  480,  490,  500],
       [ 510,  520,  530,  540,  550],
       [ 560,  570,  580,  590,  600],
       [ 610,  620,  630,  640,  650],
       [ 660,  670,  680,  690,  700],
       [ 710,  720,  730,  740,  750],
       [ 760,  770,  780,  790,  800],
       [ 810,  820,  830,  840,  850],
       [ 860,  870,  880,  890,  900],
       [ 910,  920,  930,  940,  950],
       [ 960,  970,  980,  990, 1000]])

In [28]:
a3.dtype

dtype('int32')

In [30]:
#Creating a array of float values.
f_list = [2.34, 5.67,8.90,10.35]
af = np.array(f_list)
af

array([ 2.34,  5.67,  8.9 , 10.35])

In [31]:
af.dtype

dtype('float64')

In [32]:
af.nbytes

32

In [ ]:
#1 float value takes 8 bytes of space.

# Efficient Memory Management

#### Integers

In [35]:
a1.dtype

dtype('int32')

In [39]:
a2_new = np.array(range(5,101,5),dtype = np.int8)
a2_new


array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100], dtype=int8)

In [40]:
a2_new.dtype

dtype('int8')

#### Strings or categorical data

In [43]:
names = ['Vijay','Himanshu','Kajol','Akash','Swagath','Dhivya','Pavithra','Gaya']
ar_name = np.array(names)
ar_name = ar_name.reshape((4,2))
ar_name

array([['Vijay', 'Himanshu'],
       ['Kajol', 'Akash'],
       ['Swagath', 'Dhivya'],
       ['Pavithra', 'Gaya']], dtype='<U8')

In [44]:
ar_name.dtype   

dtype('<U8')

**np.full(shape, fill_value, dtype)**

In [47]:
a_ex1 = np.full((3,3),'Himanshu',dtype = str)  #because in numpy(2D), str does not provide flexible amount of space to the string data.
a_ex1

array([['H', 'H', 'H'],
       ['H', 'H', 'H'],
       ['H', 'H', 'H']], dtype='<U1')

In [ ]:
#Object datatype provides flexible or variable amount of memry space for the data. 

In [49]:
a_ex2 = np.full((3,3),'Himanshu',dtype = np.object_) # default dataype of string data in n-dimensional data is Object (O or U).
a_ex2

array([['Himanshu', 'Himanshu', 'Himanshu'],
       ['Himanshu', 'Himanshu', 'Himanshu'],
       ['Himanshu', 'Himanshu', 'Himanshu']], dtype=object)

In [51]:
a_ex2.dtype

dtype('O')

In [52]:
a_ex3 = np.full((3,3),'This data Science course is very complex and big.',dtype = np.object_)
a_ex3

array([['This data Science course is very complex and big.',
        'This data Science course is very complex and big.',
        'This data Science course is very complex and big.'],
       ['This data Science course is very complex and big.',
        'This data Science course is very complex and big.',
        'This data Science course is very complex and big.'],
       ['This data Science course is very complex and big.',
        'This data Science course is very complex and big.',
        'This data Science course is very complex and big.']],
      dtype=object)

**np.arange() is a combination of array and range**

In [53]:
a101 = np.array(range(10,101,10))
a101

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [54]:
a102 = np.arange(10,101,10)
a102

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [55]:
a102 = a102.reshape((2,5))  #2 rows, 5 columns
a102

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

**Transposing an array**

In [56]:
a102_t = a102.T            #5rows, 2 columns
a102_t

array([[ 10,  60],
       [ 20,  70],
       [ 30,  80],
       [ 40,  90],
       [ 50, 100]])

### What is the difference between Broadcasting and Vectorization?

In [ ]:
#Broadcasting means performing same or different operations on multiple elements at the same time.

In [ ]:
#Broadcasting is a very useful, efficient and fast method to do operations. 
#If Broadcasting was allowed in base python, then looping was not all needed.

In [57]:
l = [10,20,30,40,50]  #divide every element by 5
l/5

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
#Broadcasting

In [59]:
l =[1,1,1,2000,3000,4000]
#by mistake, we have entered wrong values in the first three indexes..Please replace all the 1s with 1000.
l[0:3] = 1000    #we are providing single value to multiple indexes at the same time.


TypeError: can only assign an iterable

In [60]:
#Vectorization
l[0:3] = [1000,1000,1000]

In [61]:
l

[1000, 1000, 1000, 2000, 3000, 4000]

In [58]:
l = [2,'Swagath',5]
l[1] = 'Akash'            #indexing/slicing        [indexes] : slicers
l

[2, 'Akash', 5]

# BUT, Broadcasting is allowed in Numpy Arrays:

In [62]:
a5 = np.arange(5,101,5)
a5 = a5.reshape((4,5))
a5

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100]])

**Because broadcasting is allowed in arrays, NO NEED OF USING LOOPING.**

In [63]:
a5_updated = a5*10
a5_updated

array([[  50,  100,  150,  200,  250],
       [ 300,  350,  400,  450,  500],
       [ 550,  600,  650,  700,  750],
       [ 800,  850,  900,  950, 1000]])

In [64]:
#Vectorization
a6 = np.arange(5,101,5)
a6 = a6.reshape((4,5))
a6

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100]])

In [65]:
result_a = a5_updated - a6
result_a

array([[ 45,  90, 135, 180, 225],
       [270, 315, 360, 405, 450],
       [495, 540, 585, 630, 675],
       [720, 765, 810, 855, 900]])